version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TimeAttack
      MYSQL_USER: server
      MYSQL_PASSWORD: serverpassword
    volumes:
      - ./database:/var/lib/mysql